### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by lyc1995452-star** [ZhiningLiu1998/awesome-imbalanced-learning#2]
你好，我看了你写的这个，我是学习语义分割的，对于有些数据确实存在类别不平衡，但是这些能在代码本身进行修改吗？我好像没看到你的这个怎么进行处理的，谢谢！

**Comment by ZhiningLiu1998** [comment]
不好意思，看不懂你的问题是什么。。。请说明你的具体问题再open new issue，谢谢。

**Comment by lyc1995452-star** [comment]
你好，请问你知道如何对像素进行统计然后求比值吗？
