### ISSUE TITLE
大神看看能否加上NeurIPS 2020上的一份工作

### ISSUE THREAD

**Issue by AshinZeng** [ZhiningLiu1998/awesome-imbalanced-learning#3]
NeurIPS 2020 | 数据类别不平衡/长尾分布？不妨利用半监督或自监督学习 - 知乎
https://zhuanlan.zhihu.com/p/259710601

YyzHarry/imbalanced-semi-self: [NeurIPS 2020] Semi-Supervision (Unlabeled Data) & Self-Supervision Improve Class-Imbalanced / Long-Tailed Learning
https://github.com/YyzHarry/imbalanced-semi-self

**Comment by ZhiningLiu1998** [comment]
感谢提醒，最近事情比较多，过几天我会整理一下新的工作update上来。或者您可以直接提交一份PR，thanks！

**Comment by ZhiningLiu1998** [comment]
Please check the update, thanks!

**Comment by ZhiningLiu1998** [comment]
@all-contributors please add @AshinZeng for the maintenance
