### ISSUE TITLE
Applications that use Imbalanced dataset

### ISSUE THREAD

**Issue by DhavalRepo18** [ZhiningLiu1998/awesome-imbalanced-learning#9]
Can we add the application paper that use the class imbalances. 

For example, https://ieeexplore.ieee.org/abstract/document/9378369/ Predictive Modeling

**Comment by ZhiningLiu1998** [comment]
Hi Dhaval,

Thanks for your advice! I've read the abstract of this paper, but I'm not sure how does it related to imbalanced learning. It seems that this paper is more about designing an auto ml system for IoT applications. 

So you might be interested in this repository: https://github.com/phodal/awesome-iot. 
Hope this helps you.
